/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ApplicantRouteImport } from './routes/applicant'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApplicantIndexRouteImport } from './routes/applicant.index'
import { Route as ApplicantShowsRouteImport } from './routes/applicant.shows'

const ApplicantRoute = ApplicantRouteImport.update({
  id: '/applicant',
  path: '/applicant',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicantIndexRoute = ApplicantIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ApplicantRoute,
} as any)
const ApplicantShowsRoute = ApplicantShowsRouteImport.update({
  id: '/shows',
  path: '/shows',
  getParentRoute: () => ApplicantRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/applicant': typeof ApplicantRouteWithChildren
  '/applicant/shows': typeof ApplicantShowsRoute
  '/applicant/': typeof ApplicantIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/applicant/shows': typeof ApplicantShowsRoute
  '/applicant': typeof ApplicantIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/applicant': typeof ApplicantRouteWithChildren
  '/applicant/shows': typeof ApplicantShowsRoute
  '/applicant/': typeof ApplicantIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/applicant' | '/applicant/shows' | '/applicant/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/applicant/shows' | '/applicant'
  id: '__root__' | '/' | '/applicant' | '/applicant/shows' | '/applicant/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApplicantRoute: typeof ApplicantRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/applicant': {
      id: '/applicant'
      path: '/applicant'
      fullPath: '/applicant'
      preLoaderRoute: typeof ApplicantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/applicant/': {
      id: '/applicant/'
      path: '/'
      fullPath: '/applicant/'
      preLoaderRoute: typeof ApplicantIndexRouteImport
      parentRoute: typeof ApplicantRoute
    }
    '/applicant/shows': {
      id: '/applicant/shows'
      path: '/shows'
      fullPath: '/applicant/shows'
      preLoaderRoute: typeof ApplicantShowsRouteImport
      parentRoute: typeof ApplicantRoute
    }
  }
}

interface ApplicantRouteChildren {
  ApplicantShowsRoute: typeof ApplicantShowsRoute
  ApplicantIndexRoute: typeof ApplicantIndexRoute
}

const ApplicantRouteChildren: ApplicantRouteChildren = {
  ApplicantShowsRoute: ApplicantShowsRoute,
  ApplicantIndexRoute: ApplicantIndexRoute,
}

const ApplicantRouteWithChildren = ApplicantRoute._addFileChildren(
  ApplicantRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApplicantRoute: ApplicantRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
