/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProducerRouteImport } from './routes/producer'
import { Route as ApplicantRouteImport } from './routes/applicant'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProducerIndexRouteImport } from './routes/producer.index'
import { Route as ApplicantIndexRouteImport } from './routes/applicant.index'
import { Route as ProducerShowsRouteImport } from './routes/producer.shows'
import { Route as ApplicantShowsRouteImport } from './routes/applicant.shows'
import { Route as ApplicantProfileRouteImport } from './routes/applicant.profile'
import { Route as ApplicantFilesRouteImport } from './routes/applicant.files'
import { Route as ApplicantApplicationsRouteImport } from './routes/applicant.applications'
import { Route as ProducerShowsIdRouteImport } from './routes/producer.shows.$id'
import { Route as ApplicantShowsIdRouteImport } from './routes/applicant.shows.$id'
import { Route as ApplicantShowsIdCompleteRouteImport } from './routes/applicant.shows.$id.complete'
import { Route as ApplicantShowsIdApplyRouteImport } from './routes/applicant.shows.$id.apply'

const ProducerRoute = ProducerRouteImport.update({
  id: '/producer',
  path: '/producer',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicantRoute = ApplicantRouteImport.update({
  id: '/applicant',
  path: '/applicant',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProducerIndexRoute = ProducerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProducerRoute,
} as any)
const ApplicantIndexRoute = ApplicantIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ApplicantRoute,
} as any)
const ProducerShowsRoute = ProducerShowsRouteImport.update({
  id: '/shows',
  path: '/shows',
  getParentRoute: () => ProducerRoute,
} as any)
const ApplicantShowsRoute = ApplicantShowsRouteImport.update({
  id: '/shows',
  path: '/shows',
  getParentRoute: () => ApplicantRoute,
} as any)
const ApplicantProfileRoute = ApplicantProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => ApplicantRoute,
} as any)
const ApplicantFilesRoute = ApplicantFilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => ApplicantRoute,
} as any)
const ApplicantApplicationsRoute = ApplicantApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => ApplicantRoute,
} as any)
const ProducerShowsIdRoute = ProducerShowsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ProducerShowsRoute,
} as any)
const ApplicantShowsIdRoute = ApplicantShowsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApplicantShowsRoute,
} as any)
const ApplicantShowsIdCompleteRoute =
  ApplicantShowsIdCompleteRouteImport.update({
    id: '/complete',
    path: '/complete',
    getParentRoute: () => ApplicantShowsIdRoute,
  } as any)
const ApplicantShowsIdApplyRoute = ApplicantShowsIdApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => ApplicantShowsIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/applicant': typeof ApplicantRouteWithChildren
  '/producer': typeof ProducerRouteWithChildren
  '/applicant/applications': typeof ApplicantApplicationsRoute
  '/applicant/files': typeof ApplicantFilesRoute
  '/applicant/profile': typeof ApplicantProfileRoute
  '/applicant/shows': typeof ApplicantShowsRouteWithChildren
  '/producer/shows': typeof ProducerShowsRouteWithChildren
  '/applicant/': typeof ApplicantIndexRoute
  '/producer/': typeof ProducerIndexRoute
  '/applicant/shows/$id': typeof ApplicantShowsIdRouteWithChildren
  '/producer/shows/$id': typeof ProducerShowsIdRoute
  '/applicant/shows/$id/apply': typeof ApplicantShowsIdApplyRoute
  '/applicant/shows/$id/complete': typeof ApplicantShowsIdCompleteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/applicant/applications': typeof ApplicantApplicationsRoute
  '/applicant/files': typeof ApplicantFilesRoute
  '/applicant/profile': typeof ApplicantProfileRoute
  '/applicant/shows': typeof ApplicantShowsRouteWithChildren
  '/producer/shows': typeof ProducerShowsRouteWithChildren
  '/applicant': typeof ApplicantIndexRoute
  '/producer': typeof ProducerIndexRoute
  '/applicant/shows/$id': typeof ApplicantShowsIdRouteWithChildren
  '/producer/shows/$id': typeof ProducerShowsIdRoute
  '/applicant/shows/$id/apply': typeof ApplicantShowsIdApplyRoute
  '/applicant/shows/$id/complete': typeof ApplicantShowsIdCompleteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/applicant': typeof ApplicantRouteWithChildren
  '/producer': typeof ProducerRouteWithChildren
  '/applicant/applications': typeof ApplicantApplicationsRoute
  '/applicant/files': typeof ApplicantFilesRoute
  '/applicant/profile': typeof ApplicantProfileRoute
  '/applicant/shows': typeof ApplicantShowsRouteWithChildren
  '/producer/shows': typeof ProducerShowsRouteWithChildren
  '/applicant/': typeof ApplicantIndexRoute
  '/producer/': typeof ProducerIndexRoute
  '/applicant/shows/$id': typeof ApplicantShowsIdRouteWithChildren
  '/producer/shows/$id': typeof ProducerShowsIdRoute
  '/applicant/shows/$id/apply': typeof ApplicantShowsIdApplyRoute
  '/applicant/shows/$id/complete': typeof ApplicantShowsIdCompleteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/applicant'
    | '/producer'
    | '/applicant/applications'
    | '/applicant/files'
    | '/applicant/profile'
    | '/applicant/shows'
    | '/producer/shows'
    | '/applicant/'
    | '/producer/'
    | '/applicant/shows/$id'
    | '/producer/shows/$id'
    | '/applicant/shows/$id/apply'
    | '/applicant/shows/$id/complete'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/applicant/applications'
    | '/applicant/files'
    | '/applicant/profile'
    | '/applicant/shows'
    | '/producer/shows'
    | '/applicant'
    | '/producer'
    | '/applicant/shows/$id'
    | '/producer/shows/$id'
    | '/applicant/shows/$id/apply'
    | '/applicant/shows/$id/complete'
  id:
    | '__root__'
    | '/'
    | '/applicant'
    | '/producer'
    | '/applicant/applications'
    | '/applicant/files'
    | '/applicant/profile'
    | '/applicant/shows'
    | '/producer/shows'
    | '/applicant/'
    | '/producer/'
    | '/applicant/shows/$id'
    | '/producer/shows/$id'
    | '/applicant/shows/$id/apply'
    | '/applicant/shows/$id/complete'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApplicantRoute: typeof ApplicantRouteWithChildren
  ProducerRoute: typeof ProducerRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/producer': {
      id: '/producer'
      path: '/producer'
      fullPath: '/producer'
      preLoaderRoute: typeof ProducerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/applicant': {
      id: '/applicant'
      path: '/applicant'
      fullPath: '/applicant'
      preLoaderRoute: typeof ApplicantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/producer/': {
      id: '/producer/'
      path: '/'
      fullPath: '/producer/'
      preLoaderRoute: typeof ProducerIndexRouteImport
      parentRoute: typeof ProducerRoute
    }
    '/applicant/': {
      id: '/applicant/'
      path: '/'
      fullPath: '/applicant/'
      preLoaderRoute: typeof ApplicantIndexRouteImport
      parentRoute: typeof ApplicantRoute
    }
    '/producer/shows': {
      id: '/producer/shows'
      path: '/shows'
      fullPath: '/producer/shows'
      preLoaderRoute: typeof ProducerShowsRouteImport
      parentRoute: typeof ProducerRoute
    }
    '/applicant/shows': {
      id: '/applicant/shows'
      path: '/shows'
      fullPath: '/applicant/shows'
      preLoaderRoute: typeof ApplicantShowsRouteImport
      parentRoute: typeof ApplicantRoute
    }
    '/applicant/profile': {
      id: '/applicant/profile'
      path: '/profile'
      fullPath: '/applicant/profile'
      preLoaderRoute: typeof ApplicantProfileRouteImport
      parentRoute: typeof ApplicantRoute
    }
    '/applicant/files': {
      id: '/applicant/files'
      path: '/files'
      fullPath: '/applicant/files'
      preLoaderRoute: typeof ApplicantFilesRouteImport
      parentRoute: typeof ApplicantRoute
    }
    '/applicant/applications': {
      id: '/applicant/applications'
      path: '/applications'
      fullPath: '/applicant/applications'
      preLoaderRoute: typeof ApplicantApplicationsRouteImport
      parentRoute: typeof ApplicantRoute
    }
    '/producer/shows/$id': {
      id: '/producer/shows/$id'
      path: '/$id'
      fullPath: '/producer/shows/$id'
      preLoaderRoute: typeof ProducerShowsIdRouteImport
      parentRoute: typeof ProducerShowsRoute
    }
    '/applicant/shows/$id': {
      id: '/applicant/shows/$id'
      path: '/$id'
      fullPath: '/applicant/shows/$id'
      preLoaderRoute: typeof ApplicantShowsIdRouteImport
      parentRoute: typeof ApplicantShowsRoute
    }
    '/applicant/shows/$id/complete': {
      id: '/applicant/shows/$id/complete'
      path: '/complete'
      fullPath: '/applicant/shows/$id/complete'
      preLoaderRoute: typeof ApplicantShowsIdCompleteRouteImport
      parentRoute: typeof ApplicantShowsIdRoute
    }
    '/applicant/shows/$id/apply': {
      id: '/applicant/shows/$id/apply'
      path: '/apply'
      fullPath: '/applicant/shows/$id/apply'
      preLoaderRoute: typeof ApplicantShowsIdApplyRouteImport
      parentRoute: typeof ApplicantShowsIdRoute
    }
  }
}

interface ApplicantShowsIdRouteChildren {
  ApplicantShowsIdApplyRoute: typeof ApplicantShowsIdApplyRoute
  ApplicantShowsIdCompleteRoute: typeof ApplicantShowsIdCompleteRoute
}

const ApplicantShowsIdRouteChildren: ApplicantShowsIdRouteChildren = {
  ApplicantShowsIdApplyRoute: ApplicantShowsIdApplyRoute,
  ApplicantShowsIdCompleteRoute: ApplicantShowsIdCompleteRoute,
}

const ApplicantShowsIdRouteWithChildren =
  ApplicantShowsIdRoute._addFileChildren(ApplicantShowsIdRouteChildren)

interface ApplicantShowsRouteChildren {
  ApplicantShowsIdRoute: typeof ApplicantShowsIdRouteWithChildren
}

const ApplicantShowsRouteChildren: ApplicantShowsRouteChildren = {
  ApplicantShowsIdRoute: ApplicantShowsIdRouteWithChildren,
}

const ApplicantShowsRouteWithChildren = ApplicantShowsRoute._addFileChildren(
  ApplicantShowsRouteChildren,
)

interface ApplicantRouteChildren {
  ApplicantApplicationsRoute: typeof ApplicantApplicationsRoute
  ApplicantFilesRoute: typeof ApplicantFilesRoute
  ApplicantProfileRoute: typeof ApplicantProfileRoute
  ApplicantShowsRoute: typeof ApplicantShowsRouteWithChildren
  ApplicantIndexRoute: typeof ApplicantIndexRoute
}

const ApplicantRouteChildren: ApplicantRouteChildren = {
  ApplicantApplicationsRoute: ApplicantApplicationsRoute,
  ApplicantFilesRoute: ApplicantFilesRoute,
  ApplicantProfileRoute: ApplicantProfileRoute,
  ApplicantShowsRoute: ApplicantShowsRouteWithChildren,
  ApplicantIndexRoute: ApplicantIndexRoute,
}

const ApplicantRouteWithChildren = ApplicantRoute._addFileChildren(
  ApplicantRouteChildren,
)

interface ProducerShowsRouteChildren {
  ProducerShowsIdRoute: typeof ProducerShowsIdRoute
}

const ProducerShowsRouteChildren: ProducerShowsRouteChildren = {
  ProducerShowsIdRoute: ProducerShowsIdRoute,
}

const ProducerShowsRouteWithChildren = ProducerShowsRoute._addFileChildren(
  ProducerShowsRouteChildren,
)

interface ProducerRouteChildren {
  ProducerShowsRoute: typeof ProducerShowsRouteWithChildren
  ProducerIndexRoute: typeof ProducerIndexRoute
}

const ProducerRouteChildren: ProducerRouteChildren = {
  ProducerShowsRoute: ProducerShowsRouteWithChildren,
  ProducerIndexRoute: ProducerIndexRoute,
}

const ProducerRouteWithChildren = ProducerRoute._addFileChildren(
  ProducerRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApplicantRoute: ApplicantRouteWithChildren,
  ProducerRoute: ProducerRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
